package parser;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OV = 17;
  public static final int ELSE = 28;
  public static final int PLUS = 10;
  public static final int CLOSE = 21;
  public static final int INT = 3;
  public static final int THEN = 7;
  public static final int end = 24;
  public static final int WHILE = 6;
  public static final int DIVISION = 13;
  public static final int ERROR = 26;
  public static final int MZ = 20;
  public static final int VZ = 19;
  public static final int IF = 5;
  public static final int ID = 8;
  public static final int PROGRAM = 2;
  public static final int EQUALS = 25;
  public static final int STRING = 4;
  public static final int COMMA = 27;
  public static final int EOF = 0;
  public static final int MULTIPLICATION = 11;
  public static final int MINUS = 12;
  public static final int CONST = 9;
  public static final int ZZ = 16;
  public static final int error = 1;
  public static final int ASSIGN = 14;
  public static final int ZV = 18;
  public static final int OPEN = 22;
  public static final int begin = 23;
  public static final int OZ = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAM",
  "INT",
  "STRING",
  "IF",
  "WHILE",
  "THEN",
  "ID",
  "CONST",
  "PLUS",
  "MULTIPLICATION",
  "MINUS",
  "DIVISION",
  "ASSIGN",
  "OZ",
  "ZZ",
  "OV",
  "ZV",
  "VZ",
  "MZ",
  "CLOSE",
  "OPEN",
  "begin",
  "end",
  "EQUALS",
  "ERROR",
  "COMMA",
  "ELSE"
  };
}

